# This is a basic workflow to help you get started with Actions

name: CI
run-name: ${{ github.actor }} is testing out GitHub Actions
# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  GITHUB_ACTIONS: true

jobs:
  github-task-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "GITHUB_ACTIONS is set to ${{ env.GITHUB_ACTIONS }}"
      - run: echo "Name of the branch ${{ github.ref }} and your repository ${{ github.repository }}"
      - run: echo "Job was triggered by event ${{ github.event_name }}"
